language: node_js
node_js:
  - "8.1"     #Azure web app compability
notifications:
  on_success: change
  on_failure: always
  slack: js2018sose:Xavb1Q1dBIeFGCjiBOS1nb4c
cache:
  directories:
    - "node_modules"
deploy:
  provider: azure_web_apps
  on: develop
  verbose: true

#karma
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  karma start --browsers Firefox --single-run
